### ISSUE TITLE
Hardcoded Cloudhub Domains in IT

### ISSUE THREAD

**Issue by StoicNZ** [mulesoft/mule-maven-plugin#15]
Can't someone just create an app on "test-app-12345" "maven-plugin-cloudhub-business-group-test", "maven-plugin-cloudhub-undeploy-test" and "maven-plugin-cloudhub-deploy-test" Cloudhub domains and your integration tests are always going to fail?

**Comment by WilliamPinho** [comment]
Thanks for the comment, we've solved the issue by generating random names to the domain. https://github.com/mulesoft/mule-maven-plugin/commit/ca9ca35ed3ee8c9d1f5152b901a44519e7b17953
