### ISSUE TITLE
@since 2.3.0 is wrong for ProcessResourcesMojo.exclusions

### ISSUE THREAD

**Issue by ca-stefan-cordes** [mulesoft/mule-maven-plugin#299]
The field ProcessResourcesMojo.exclusions (and so the configuration in the pom.xml) is 
not `@since 2.3.0` because `@since 2.3.0` the name was defaultExclusions
Correct is `@since 2.3.3`

**Comment by ca-stefan-cordes** [comment]
See MMP-470

**Comment by julianpascualMuleSoft** [comment]
PR Merged
