### ISSUE TITLE
MuleLifecycleMapping refers to non existing plugin

### ISSUE THREAD

**Issue by ca-stefan-cordes** [mulesoft/mule-maven-plugin#336]
/mule-maven-plugin/mule-maven-plugin/src/main/java/org/mule/tools/maven/mojo/model/lifecycle/mapping/project/MuleLifecycleMapping.java
is referring to maven-site-plugin:3.6.1 but that is not existing.
https://search.maven.org/search?q=g:org.apache.maven.plugins%20AND%20a:maven-site-plugin&core=gav
![image](https://user-images.githubusercontent.com/50696194/68017309-bbf1f100-fc96-11e9-9e1a-6bc8d666a921.png)

Problem is that
* Create a blank new Mule4 project
* mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.1:go-offline
=> fails with
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:resolve-plugins (resolve-plugins) on project bug-xmlmodule-fails: Could not find artifact org.apache.maven.plugins:maven-site-plugin:jar:3.6.1 in centralMirror

**Comment by ca-stefan-cordes** [comment]
Workaround is to add
```
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-site-plugin</artifactId>
					<version>3.8.2</version>
				</plugin>
			</plugins>
		</pluginManagement>
```
to the pom.xml

Probably some other versions in MuleLifecycleMapping needs to be re-checked.

Best would be to not specify versions in the java sources.

**Comment by julianpascualMuleSoft** [comment]
Pull request merged, thanks Stefan!
