### ISSUE TITLE
Tag missing for 3.5.4

### ISSUE THREAD

**Issue by ca-stefan-cordes** [mulesoft/mule-maven-plugin#541]
3.5.4 is released, but no tag was set

https://repository.mulesoft.org/nexus/content/repositories/releases/org/mule/tools/maven/mule-maven-plugin/
![image](https://user-images.githubusercontent.com/50696194/152008421-0deb9de7-235d-4b0d-90f8-b1d55cae7af9.png)

https://github.com/mulesoft/mule-maven-plugin/tags
![image](https://user-images.githubusercontent.com/50696194/152008553-1d75e7dd-143e-42c4-a6ca-e0ef55c3d743.png)

**Comment by ca-stefan-cordes** [comment]
Which it makes harder to find the corresponding mule-maven-client-impl (to exclude the aether-transport-http)

**Comment by martinbjeldbak** [comment]
Hi @ca-stefan-cordes this tag now looks to have been created on February 25th at https://github.com/mulesoft/mule-maven-plugin/releases/tag/v3.5.4
